server:
  port: ${PHARMACY_SERVER_PORT:10025}

spring:
  application:
    name: pharmacy-service
  cloud:
    service-registry:
      auto-registration:
        enabled: ${NACOS_DISCOVERY_ENABLED:true}
    nacos:
      discovery:
        enabled: ${NACOS_DISCOVERY_ENABLED:true}
        register-enabled: ${NACOS_DISCOVERY_ENABLED:true}
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
  datasource:
    url: ${DB_URL:jdbc:postgresql://59.110.116.141:5432/postgres}
    username: ${DB_USERNAME:leon}
    password: ${DB_PASSWORD:YcjQe%dFF2*Ds3z7mysH4w}
    driver-class-name: org.postgresql.Driver

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
