CREATE TABLE IF NOT EXISTS patient (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_no VARCHAR(64) NOT NULL,
    name VARCHAR(64) NOT NULL,
    gender VARCHAR(16) NOT NULL,
    birth_date DATE,
    phone VARCHAR(32),
    id_card VARCHAR(32),
    blood_type VARCHAR(16),
    allergy_summary VARCHAR(255),
    history_summary TEXT,
    emergency_contact VARCHAR(64),
    emergency_phone VARCHAR(32),
    status VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_patient_patient_no ON patient (patient_no);
CREATE UNIQUE INDEX IF NOT EXISTS uk_patient_phone ON patient (phone) WHERE phone IS NOT NULL;

CREATE TABLE IF NOT EXISTS department (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dept_code VARCHAR(64) NOT NULL,
    dept_name VARCHAR(64) NOT NULL,
    dept_type VARCHAR(32),
    description VARCHAR(255),
    status VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_department_dept_code ON department (dept_code);
CREATE UNIQUE INDEX IF NOT EXISTS uk_department_dept_name ON department (dept_name);

CREATE TABLE IF NOT EXISTS doctor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_no VARCHAR(64) NOT NULL,
    name VARCHAR(64) NOT NULL,
    gender VARCHAR(16),
    title VARCHAR(64),
    department_id BIGINT NOT NULL,
    introduction TEXT,
    specialty VARCHAR(255),
    phone VARCHAR(32),
    status VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_doctor_department
        FOREIGN KEY (department_id) REFERENCES department (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_doctor_doctor_no ON doctor (doctor_no);
CREATE UNIQUE INDEX IF NOT EXISTS uk_doctor_phone ON doctor (phone) WHERE phone IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_doctor_department_id ON doctor (department_id);

CREATE TABLE IF NOT EXISTS sys_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_code VARCHAR(64) NOT NULL,
    role_name VARCHAR(64) NOT NULL,
    description VARCHAR(255),
    status VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_role_role_code ON sys_role (role_code);

CREATE TABLE IF NOT EXISTS sys_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    user_type VARCHAR(32) NOT NULL,
    biz_id BIGINT,
    real_name VARCHAR(64) NOT NULL,
    phone VARCHAR(32),
    email VARCHAR(128),
    status VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
    last_login_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_user_username ON sys_user (username);
CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_user_phone ON sys_user (phone) WHERE phone IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_sys_user_user_type_biz_id ON sys_user (user_type, biz_id);

CREATE TABLE IF NOT EXISTS sys_user_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sys_user_role_user
        FOREIGN KEY (user_id) REFERENCES sys_user (id),
    CONSTRAINT fk_sys_user_role_role
        FOREIGN KEY (role_id) REFERENCES sys_role (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_user_role_user_role ON sys_user_role (user_id, role_id);
CREATE INDEX IF NOT EXISTS idx_sys_user_role_role_id ON sys_user_role (role_id);
