-- 自动生成的表: sys_permission
CREATE TABLE IF NOT EXISTS sys_permission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permission_code VARCHAR(128) NOT NULL,
    permission_name VARCHAR(128) NOT NULL,
    permission_type VARCHAR(32) NOT NULL,
    description VARCHAR(255),
    status VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

-- 自动生成的表: sys_role_permission
CREATE TABLE IF NOT EXISTS sys_role_permission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 自动生成的表: sys_menu
CREATE TABLE IF NOT EXISTS sys_menu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT,
    menu_name VARCHAR(64) NOT NULL,
    menu_type VARCHAR(32) NOT NULL,
    route_path VARCHAR(128),
    component_path VARCHAR(255),
    permission_code VARCHAR(128),
    sort_no INTEGER,
    icon VARCHAR(64),
    status VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

-- 自动生成的表: sys_operation_log
CREATE TABLE IF NOT EXISTS sys_operation_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    username VARCHAR(64),
    biz_type VARCHAR(64) NOT NULL,
    biz_id BIGINT,
    operation_type VARCHAR(64) NOT NULL,
    request_uri VARCHAR(255),
    request_method VARCHAR(16),
    operation_desc VARCHAR(255),
    ip_address VARCHAR(64),
    result_status VARCHAR(32) NOT NULL,
    error_message TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

-- 自动生成的表: sys_dict_type
CREATE TABLE IF NOT EXISTS sys_dict_type (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dict_code VARCHAR(64) NOT NULL,
    dict_name VARCHAR(64) NOT NULL,
    description VARCHAR(255),
    status VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

-- 自动生成的表: sys_dict_item
CREATE TABLE IF NOT EXISTS sys_dict_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dict_type_id BIGINT NOT NULL,
    item_code VARCHAR(64) NOT NULL,
    item_name VARCHAR(64) NOT NULL,
    item_value VARCHAR(128) NOT NULL,
    sort_no INTEGER,
    status VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

-- 自动生成的表: doctor_schedule
CREATE TABLE IF NOT EXISTS doctor_schedule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_id BIGINT NOT NULL,
    department_id BIGINT NOT NULL,
    schedule_date DATE NOT NULL,
    time_slot VARCHAR(16) NOT NULL,
    source_count INTEGER NOT NULL,
    available_count INTEGER NOT NULL,
    fee_amount NUMERIC(10,2) NOT NULL,
    source_type VARCHAR(32),
    status VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

-- 自动生成的表: registration
CREATE TABLE IF NOT EXISTS registration (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration_no VARCHAR(64) NOT NULL,
    patient_id BIGINT NOT NULL,
    doctor_id BIGINT NOT NULL,
    department_id BIGINT NOT NULL,
    schedule_id BIGINT NOT NULL,
    visit_date DATE NOT NULL,
    time_slot VARCHAR(16) NOT NULL,
    queue_no INTEGER,
    source_type VARCHAR(32),
    status VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
    fee_amount NUMERIC(10,2) NOT NULL,
    cancel_reason VARCHAR(255),
    registered_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

-- 自动生成的表: visit_queue
CREATE TABLE IF NOT EXISTS visit_queue (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration_id BIGINT NOT NULL,
    doctor_id BIGINT NOT NULL,
    queue_no INTEGER NOT NULL,
    queue_status VARCHAR(32) NOT NULL,
    called_at TIMESTAMP,
    finished_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

-- 自动生成的表: medical_record
CREATE TABLE IF NOT EXISTS medical_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_no VARCHAR(64) NOT NULL,
    patient_id BIGINT NOT NULL,
    doctor_id BIGINT NOT NULL,
    department_id BIGINT NOT NULL,
    registration_id BIGINT NOT NULL,
    chief_complaint TEXT NOT NULL,
    present_illness TEXT,
    past_history TEXT,
    allergy_history TEXT,
    physical_exam TEXT,
    preliminary_diagnosis TEXT,
    final_diagnosis TEXT,
    advice TEXT,
    status VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
    confirmed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

-- 自动生成的表: medical_diagnosis
CREATE TABLE IF NOT EXISTS medical_diagnosis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medical_record_id BIGINT NOT NULL,
    diagnosis_type VARCHAR(32) NOT NULL,
    diagnosis_code VARCHAR(64),
    diagnosis_name VARCHAR(128) NOT NULL,
    diagnosis_desc VARCHAR(255),
    sort_no INTEGER,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

-- 自动生成的表: check_request
CREATE TABLE IF NOT EXISTS check_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_no VARCHAR(64) NOT NULL,
    patient_id BIGINT NOT NULL,
    registration_id BIGINT NOT NULL,
    medical_record_id BIGINT,
    doctor_id BIGINT NOT NULL,
    department_id BIGINT NOT NULL,
    target_department_id BIGINT NOT NULL,
    check_item_code VARCHAR(64) NOT NULL,
    check_item_name VARCHAR(128) NOT NULL,
    clinical_diagnosis VARCHAR(255),
    purpose VARCHAR(255),
    urgent_flag BOOLEAN NOT NULL,
    fee_amount NUMERIC(10,2) NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
    result_summary TEXT,
    requested_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

-- 自动生成的表: inspection_request
CREATE TABLE IF NOT EXISTS inspection_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_no VARCHAR(64) NOT NULL,
    patient_id BIGINT NOT NULL,
    registration_id BIGINT NOT NULL,
    medical_record_id BIGINT,
    doctor_id BIGINT NOT NULL,
    department_id BIGINT NOT NULL,
    target_department_id BIGINT NOT NULL,
    inspection_item_code VARCHAR(64) NOT NULL,
    inspection_item_name VARCHAR(128) NOT NULL,
    sample_type VARCHAR(64),
    urgent_flag BOOLEAN NOT NULL,
    fee_amount NUMERIC(10,2) NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
    result_summary TEXT,
    requested_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

-- 自动生成的表: disposal_request
CREATE TABLE IF NOT EXISTS disposal_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_no VARCHAR(64) NOT NULL,
    patient_id BIGINT NOT NULL,
    registration_id BIGINT NOT NULL,
    medical_record_id BIGINT,
    doctor_id BIGINT NOT NULL,
    department_id BIGINT NOT NULL,
    disposal_item_code VARCHAR(64) NOT NULL,
    disposal_item_name VARCHAR(128) NOT NULL,
    quantity INTEGER,
    remark VARCHAR(255),
    status VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

-- 自动生成的表: check_result
CREATE TABLE IF NOT EXISTS check_result (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    check_request_id BIGINT NOT NULL,
    report_no VARCHAR(64) NOT NULL,
    result_text TEXT,
    result_summary TEXT,
    conclusion TEXT,
    report_file_id BIGINT,
    report_doctor_id BIGINT,
    reported_at TIMESTAMP,
    status VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

-- 自动生成的表: inspection_result
CREATE TABLE IF NOT EXISTS inspection_result (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inspection_request_id BIGINT NOT NULL,
    report_no VARCHAR(64) NOT NULL,
    summary TEXT,
    conclusion TEXT,
    report_file_id BIGINT,
    report_doctor_id BIGINT,
    reported_at TIMESTAMP,
    status VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

-- 自动生成的表: inspection_result_item
CREATE TABLE IF NOT EXISTS inspection_result_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inspection_result_id BIGINT NOT NULL,
    item_code VARCHAR(64) NOT NULL,
    item_name VARCHAR(128) NOT NULL,
    result_value VARCHAR(64) NOT NULL,
    unit VARCHAR(32),
    reference_range VARCHAR(64),
    abnormal_flag VARCHAR(16),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

-- 自动生成的表: prescription
CREATE TABLE IF NOT EXISTS prescription (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prescription_no VARCHAR(64) NOT NULL,
    patient_id BIGINT NOT NULL,
    registration_id BIGINT NOT NULL,
    medical_record_id BIGINT,
    doctor_id BIGINT NOT NULL,
    department_id BIGINT NOT NULL,
    prescription_type VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
    total_amount NUMERIC(10,2) NOT NULL,
    remark VARCHAR(255),
    issued_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

-- 自动生成的表: prescription_item
CREATE TABLE IF NOT EXISTS prescription_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prescription_id BIGINT NOT NULL,
    drug_id BIGINT NOT NULL,
    drug_name VARCHAR(128) NOT NULL,
    specification VARCHAR(128),
    dosage VARCHAR(64),
    frequency VARCHAR(64),
    days INTEGER,
    quantity INTEGER NOT NULL,
    unit_price NUMERIC(10,2) NOT NULL,
    amount NUMERIC(10,2) NOT NULL,
    usage_method VARCHAR(128),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

-- 自动生成的表: drug_info
CREATE TABLE IF NOT EXISTS drug_info (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    drug_code VARCHAR(64) NOT NULL,
    drug_name VARCHAR(128) NOT NULL,
    generic_name VARCHAR(128),
    specification VARCHAR(128),
    unit VARCHAR(32),
    category VARCHAR(64),
    manufacturer VARCHAR(128),
    sale_price NUMERIC(10,2) NOT NULL,
    stock_quantity INTEGER NOT NULL,
    warning_quantity INTEGER,
    contraindication TEXT,
    status VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

-- 自动生成的表: drug_dispense_record
CREATE TABLE IF NOT EXISTS drug_dispense_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prescription_id BIGINT NOT NULL,
    patient_id BIGINT NOT NULL,
    operator_id BIGINT NOT NULL,
    dispense_type VARCHAR(32) NOT NULL,
    quantity INTEGER,
    status VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
    operate_time TIMESTAMP NOT NULL,
    remark VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

-- 自动生成的表: payment_order
CREATE TABLE IF NOT EXISTS payment_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no VARCHAR(64) NOT NULL,
    patient_id BIGINT NOT NULL,
    registration_id BIGINT,
    order_type VARCHAR(32) NOT NULL,
    total_amount NUMERIC(10,2) NOT NULL,
    paid_amount NUMERIC(10,2) NOT NULL,
    pay_status VARCHAR(32) NOT NULL,
    pay_channel VARCHAR(32),
    pay_time TIMESTAMP,
    cashier_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

-- 自动生成的表: payment_item
CREATE TABLE IF NOT EXISTS payment_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_order_id BIGINT NOT NULL,
    item_type VARCHAR(32) NOT NULL,
    biz_id BIGINT NOT NULL,
    item_name VARCHAR(128) NOT NULL,
    unit_price NUMERIC(10,2) NOT NULL,
    quantity INTEGER NOT NULL,
    amount NUMERIC(10,2) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

-- 自动生成的表: refund_record
CREATE TABLE IF NOT EXISTS refund_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_order_id BIGINT NOT NULL,
    refund_no VARCHAR(64) NOT NULL,
    refund_amount NUMERIC(10,2) NOT NULL,
    refund_reason VARCHAR(255),
    operator_id BIGINT,
    refund_time TIMESTAMP NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

-- 自动生成的表: ai_chat_session
CREATE TABLE IF NOT EXISTS ai_chat_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_no VARCHAR(64) NOT NULL,
    patient_id BIGINT NOT NULL,
    registration_id BIGINT,
    session_type VARCHAR(32) NOT NULL,
    summary TEXT,
    status VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
    started_at TIMESTAMP NOT NULL,
    ended_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

-- 自动生成的表: ai_chat_message
CREATE TABLE IF NOT EXISTS ai_chat_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    message_role VARCHAR(16) NOT NULL,
    message_content TEXT NOT NULL,
    risk_level VARCHAR(32),
    sequence_no INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 自动生成的表: ai_triage_result
CREATE TABLE IF NOT EXISTS ai_triage_result (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    patient_id BIGINT NOT NULL,
    recommended_department_id BIGINT,
    candidate_departments JSONB,
    reason_text TEXT,
    risk_level VARCHAR(32),
    advice_text TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 自动生成的表: ai_medical_record_draft
CREATE TABLE IF NOT EXISTS ai_medical_record_draft (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    registration_id BIGINT,
    medical_record_id BIGINT,
    source_session_id BIGINT,
    draft_content TEXT NOT NULL,
    draft_type VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 自动生成的表: ai_diagnosis_advice
CREATE TABLE IF NOT EXISTS ai_diagnosis_advice (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    registration_id BIGINT,
    medical_record_id BIGINT,
    advice_text TEXT NOT NULL,
    risk_level VARCHAR(32),
    reference_sources JSONB,
    confirmed_by_doctor BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 自动生成的表: ai_call_log
CREATE TABLE IF NOT EXISTS ai_call_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT,
    biz_type VARCHAR(64) NOT NULL,
    model_name VARCHAR(128),
    prompt_summary TEXT,
    tool_called JSONB,
    token_usage INTEGER,
    response_status VARCHAR(32) NOT NULL,
    error_message TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 自动生成的表: knowledge_document
CREATE TABLE IF NOT EXISTS knowledge_document (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_no VARCHAR(64) NOT NULL,
    title VARCHAR(255) NOT NULL,
    category VARCHAR(64),
    file_id BIGINT NOT NULL,
    source_type VARCHAR(32),
    status VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
    uploaded_by BIGINT,
    uploaded_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

-- 自动生成的表: knowledge_chunk
CREATE TABLE IF NOT EXISTS knowledge_chunk (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    chunk_no INTEGER NOT NULL,
    chunk_text TEXT NOT NULL,
    token_count INTEGER,
    status VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

-- 自动生成的表: knowledge_vector
CREATE TABLE IF NOT EXISTS knowledge_vector (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chunk_id BIGINT NOT NULL,
    embedding_vector VECTOR NOT NULL,
    embedding_model VARCHAR(128),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 自动生成的表: file_record
CREATE TABLE IF NOT EXISTS file_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    biz_type VARCHAR(64),
    biz_id BIGINT,
    bucket_name VARCHAR(128) NOT NULL,
    object_key VARCHAR(255) NOT NULL,
    original_name VARCHAR(255) NOT NULL,
    file_type VARCHAR(64),
    content_type VARCHAR(128),
    file_size BIGINT NOT NULL,
    uploader_id BIGINT,
    uploaded_at TIMESTAMP NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

-- 自动生成的表: ct_image_file
CREATE TABLE IF NOT EXISTS ct_image_file (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    registration_id BIGINT,
    medical_record_id BIGINT,
    file_id BIGINT NOT NULL,
    image_type VARCHAR(32) NOT NULL,
    upload_source VARCHAR(32) NOT NULL,
    description VARCHAR(255),
    status VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
    uploaded_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

-- 自动生成的表: ct_analysis_task
CREATE TABLE IF NOT EXISTS ct_analysis_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_no VARCHAR(64) NOT NULL,
    patient_id BIGINT NOT NULL,
    registration_id BIGINT,
    medical_record_id BIGINT,
    ct_image_file_id BIGINT NOT NULL,
    analysis_type VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
    retry_count INTEGER NOT NULL,
    requested_by BIGINT,
    requested_at TIMESTAMP NOT NULL,
    finished_at TIMESTAMP,
    error_message TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

-- 自动生成的表: ct_analysis_result
CREATE TABLE IF NOT EXISTS ct_analysis_result (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL,
    has_hemorrhage BOOLEAN NOT NULL,
    confidence NUMERIC(5,4),
    risk_level VARCHAR(32),
    abnormal_slices JSONB,
    heatmap_file_id BIGINT,
    model_name VARCHAR(128),
    result_json JSONB,
    doctor_confirm_status VARCHAR(32) NOT NULL,
    confirmed_by BIGINT,
    confirmed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);
