-- 医生排班模板：按星期几 + 时段定义常规出诊，供批量自动生成 doctor_schedule
CREATE TABLE IF NOT EXISTS doctor_schedule_template (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_id BIGINT NOT NULL,
    department_id BIGINT NOT NULL,
    day_of_week INTEGER NOT NULL,
    time_slot VARCHAR(16) NOT NULL,
    source_count INTEGER NOT NULL,
    fee_amount NUMERIC(10, 2) NOT NULL,
    source_type VARCHAR(32),
    status VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_schedule_template_doctor_day_slot UNIQUE (doctor_id, day_of_week, time_slot)
);

COMMENT ON COLUMN doctor_schedule_template.day_of_week IS '1=Monday ... 7=Sunday (ISO-8601)';
