ALTER TABLE ct_analysis_task
    ADD COLUMN IF NOT EXISTS analysis_type VARCHAR(64),
    ADD COLUMN IF NOT EXISTS task_status VARCHAR(32),
    ADD COLUMN IF NOT EXISTS input_path VARCHAR(512),
    ADD COLUMN IF NOT EXISTS failure_reason TEXT,
    ADD COLUMN IF NOT EXISTS submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS started_at TIMESTAMP,
    ADD COLUMN IF NOT EXISTS finished_at TIMESTAMP,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

CREATE INDEX IF NOT EXISTS idx_ct_analysis_task_file
    ON ct_analysis_task (ct_image_file_id);

CREATE INDEX IF NOT EXISTS idx_ct_analysis_task_status
    ON ct_analysis_task (task_status);


ALTER TABLE ct_analysis_result
    ADD COLUMN IF NOT EXISTS analysis_type VARCHAR(64),
    ADD COLUMN IF NOT EXISTS predicted_category VARCHAR(32),
    ADD COLUMN IF NOT EXISTS confidence NUMERIC(10, 6),
    ADD COLUMN IF NOT EXISTS probability_b1 NUMERIC(10, 6),
    ADD COLUMN IF NOT EXISTS probability_b2 NUMERIC(10, 6),
    ADD COLUMN IF NOT EXISTS risk_level VARCHAR(32),
    ADD COLUMN IF NOT EXISTS model_name VARCHAR(128),
    ADD COLUMN IF NOT EXISTS doctor_confirm_status VARCHAR(32) DEFAULT 'UNCONFIRMED',
    ADD COLUMN IF NOT EXISTS raw_result_json TEXT,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
